import QRCode from "qrcode";

/*
 * The verification QR (Milestone 15, Req 2/5; `qrcode`, approved by the
 * founder 2026-09-29). Returns an SVG STRING — vector, so it stays crisp on a
 * printed A4 page and inside the PDF (Req 6) — encoding the certificate's
 * verification URL. The output is generated by the library from a URL that
 * this function validates first; it contains only <svg>/<path> markup, which
 * is why the component may inline it.
 *
 * Dark modules are the certificate's navy; the background is transparent so
 * the QR sits on the paper. Error correction "M" survives a small smudge or
 * scan artefact on paper without making the code dense.
 */
export async function certificateQrSvg(verifyUrl: string): Promise<string> {
  let url: URL;
  try {
    url = new URL(verifyUrl);
  } catch {
    throw new Error("certificateQrSvg: the verification URL must be absolute");
  }
  if (url.protocol !== "https:" && url.protocol !== "http:") {
    throw new Error("certificateQrSvg: the verification URL must be http(s)");
  }
  return QRCode.toString(url.toString(), {
    type: "svg",
    margin: 0,
    errorCorrectionLevel: "M",
    color: { dark: "#0b1b3a", light: "#0000" },
  });
}
