import { randomUUID } from "node:crypto";
import { afterAll, afterEach, describe, expect, it } from "vitest";
import { disconnectPrisma, getPrisma } from "@/db/prisma";
import {
  findDomainById,
  findDomainBySlug,
  listDomains,
} from "@/modules/catalogue/domains/repository";

/*
 * Integration layer (ADR-038 layer 2): runs against the REAL test database —
 * tests/setup-env.ts points DATABASE_URL at DATABASE_URL_TEST and refuses to
 * run otherwise. Milestone 1 criterion 4: "passes against real PostgreSQL —
 * not a mock".
 *
 * Each test creates its own rows with a unique code and removes them, so the
 * suite is independent of the seed and of test order.
 */
const created: string[] = [];

async function createDomain(overrides: Partial<{ code: string; name: string; slug: string }> = {}) {
  const suffix = randomUUID().slice(0, 8);
  const row = await getPrisma().domain.create({
    data: {
      code: overrides.code ?? `T${suffix.toUpperCase()}`,
      name: overrides.name ?? `Test Domain ${suffix}`,
      slug: overrides.slug ?? `test-domain-${suffix}`,
      description: "integration-test row",
    },
  });
  created.push(row.id);
  return row;
}

afterEach(async () => {
  if (created.length) {
    await getPrisma().domain.deleteMany({ where: { id: { in: created.splice(0) } } });
  }
});

afterAll(async () => {
  await disconnectPrisma();
});

describe("domains repository (real PostgreSQL)", () => {
  it("findDomainById returns the row that was written", async () => {
    const row = await createDomain();
    const found = await findDomainById(row.id);
    expect(found).not.toBeNull();
    expect(found).toMatchObject({ id: row.id, code: row.code, name: row.name, slug: row.slug });
  });

  it("findDomainById returns null for an unknown id (no throw, no fallback)", async () => {
    expect(await findDomainById(randomUUID())).toBeNull();
  });

  it("findDomainBySlug resolves the same row", async () => {
    const row = await createDomain();
    expect((await findDomainBySlug(row.slug))?.id).toBe(row.id);
  });

  it("listDomains includes newly written rows, ordered by code", async () => {
    const a = await createDomain({ code: "ZZA" });
    const b = await createDomain({ code: "ZZB" });
    const codes = (await listDomains()).map((d) => d.code);
    expect(codes.indexOf("ZZA")).toBeLessThan(codes.indexOf("ZZB"));
    expect(codes).toEqual(expect.arrayContaining([a.code, b.code]));
  });

  it("the database enforces uniqueness of code and slug (constraint, not application logic)", async () => {
    const row = await createDomain();
    await expect(
      getPrisma().domain.create({
        data: { code: row.code, name: "dup", slug: `other-${randomUUID().slice(0, 6)}` },
      }),
    ).rejects.toThrow();
    await expect(
      getPrisma().domain.create({
        data: { code: `X${randomUUID().slice(0, 6)}`, name: "dup", slug: row.slug },
      }),
    ).rejects.toThrow();
  });

  it("ids are generated by the database as UUIDs", async () => {
    const row = await createDomain();
    expect(row.id).toMatch(/^[0-9a-f-]{36}$/);
  });
});
